trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  workingDirectory: '$(Build.SourcesDirectory)/CommandAPISolution'
steps:
  - task: UseDotNet@2
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
    workingDirectory: $(workingDirectory)